/*
** Actor.Generator.cs
**
**---------------------------------------------------------------------------
** Copyright (c) 2016, David Aramant
** All rights reserved.
**
** Redistribution and use in source and binary forms, with or without
** modification, are permitted provided that the following conditions
** are met:
**
** 1. Redistributions of source code must retain the above copyright
**    notice, this list of conditions and the following disclaimer.
** 2. Redistributions in binary form must reproduce the above copyright
**    notice, this list of conditions and the following disclaimer in the
**    documentation and/or other materials provided with the distribution.
** 3. The name of the author may not be used to endorse or promote products
**    derived from this software without specific prior written permission.
**
** THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
** IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
** OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
** IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
** INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
** NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
** DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
** THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
** (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
** THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**---------------------------------------------------------------------------
**
**
*/

// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>

namespace Tiledriver.Core.Wolf3D
{
    /// <summary>
    /// Actor
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "RichEnumGenerator", "1.0.0.0" )]
    public sealed partial class Actor
    {
        private readonly string _instanceName;
        public readonly System.Int32 ID;
        public readonly System.String Category;
        public readonly System.Boolean Wolf3D;
        public readonly System.String Prefix;

        /// <summary>
        /// Player1Start
        /// </summary>
        public static readonly Actor Player1Start = new Actor(
            instanceName: "Player1Start",
            iD: 1,   
            category: "Special",   
            wolf3D: true,   
            prefix: "$"  
        );
        /// <summary>
        /// PatrolPoint
        /// </summary>
        public static readonly Actor PatrolPoint = new Actor(
            instanceName: "PatrolPoint",
            iD: 10,   
            category: "Special",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// AngelOfDeath
        /// </summary>
        public static readonly Actor AngelOfDeath = new Actor(
            instanceName: "AngelOfDeath",
            iD: 27,   
            category: "Bosses",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// DevilIncarnate
        /// </summary>
        public static readonly Actor DevilIncarnate = new Actor(
            instanceName: "DevilIncarnate",
            iD: 103,   
            category: "Bosses",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Puddle
        /// </summary>
        public static readonly Actor Puddle = new Actor(
            instanceName: "Puddle",
            iD: 33,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Puddle2
        /// </summary>
        public static readonly Actor Puddle2 = new Actor(
            instanceName: "Puddle2",
            iD: 105,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// GreenBarrel
        /// </summary>
        public static readonly Actor GreenBarrel = new Actor(
            instanceName: "GreenBarrel",
            iD: 34,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// HorizontalGreenBarrel
        /// </summary>
        public static readonly Actor HorizontalGreenBarrel = new Actor(
            instanceName: "HorizontalGreenBarrel",
            iD: 106,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// TableWithChairs
        /// </summary>
        public static readonly Actor TableWithChairs = new Actor(
            instanceName: "TableWithChairs",
            iD: 35,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// TableWithChairs2
        /// </summary>
        public static readonly Actor TableWithChairs2 = new Actor(
            instanceName: "TableWithChairs2",
            iD: 107,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// FloorLamp
        /// </summary>
        public static readonly Actor FloorLamp = new Actor(
            instanceName: "FloorLamp",
            iD: 36,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// TallFloorLamp
        /// </summary>
        public static readonly Actor TallFloorLamp = new Actor(
            instanceName: "TallFloorLamp",
            iD: 108,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Chandelier
        /// </summary>
        public static readonly Actor Chandelier = new Actor(
            instanceName: "Chandelier",
            iD: 37,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Chandelier2
        /// </summary>
        public static readonly Actor Chandelier2 = new Actor(
            instanceName: "Chandelier2",
            iD: 109,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// HangedMan
        /// </summary>
        public static readonly Actor HangedMan = new Actor(
            instanceName: "HangedMan",
            iD: 38,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// HangedMan2
        /// </summary>
        public static readonly Actor HangedMan2 = new Actor(
            instanceName: "HangedMan2",
            iD: 110,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// WhitePillar
        /// </summary>
        public static readonly Actor WhitePillar = new Actor(
            instanceName: "WhitePillar",
            iD: 40,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// CrackedPillar
        /// </summary>
        public static readonly Actor CrackedPillar = new Actor(
            instanceName: "CrackedPillar",
            iD: 112,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// GreenPlant
        /// </summary>
        public static readonly Actor GreenPlant = new Actor(
            instanceName: "GreenPlant",
            iD: 41,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// GreenPlant2
        /// </summary>
        public static readonly Actor GreenPlant2 = new Actor(
            instanceName: "GreenPlant2",
            iD: 113,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// SkeletonFlat
        /// </summary>
        public static readonly Actor SkeletonFlat = new Actor(
            instanceName: "SkeletonFlat",
            iD: 42,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// SkeletonFlat2
        /// </summary>
        public static readonly Actor SkeletonFlat2 = new Actor(
            instanceName: "SkeletonFlat2",
            iD: 114,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Sink
        /// </summary>
        public static readonly Actor Sink = new Actor(
            instanceName: "Sink",
            iD: 43,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// BrownPlant
        /// </summary>
        public static readonly Actor BrownPlant = new Actor(
            instanceName: "BrownPlant",
            iD: 44,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// BrownPlant2
        /// </summary>
        public static readonly Actor BrownPlant2 = new Actor(
            instanceName: "BrownPlant2",
            iD: 115,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Vase
        /// </summary>
        public static readonly Actor Vase = new Actor(
            instanceName: "Vase",
            iD: 45,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Vase2
        /// </summary>
        public static readonly Actor Vase2 = new Actor(
            instanceName: "Vase2",
            iD: 116,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// BareTable
        /// </summary>
        public static readonly Actor BareTable = new Actor(
            instanceName: "BareTable",
            iD: 46,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// MetalTable
        /// </summary>
        public static readonly Actor MetalTable = new Actor(
            instanceName: "MetalTable",
            iD: 117,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// CeilingLight
        /// </summary>
        public static readonly Actor CeilingLight = new Actor(
            instanceName: "CeilingLight",
            iD: 47,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// CeilingLight2
        /// </summary>
        public static readonly Actor CeilingLight2 = new Actor(
            instanceName: "CeilingLight2",
            iD: 118,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// RedCeilingLight
        /// </summary>
        public static readonly Actor RedCeilingLight = new Actor(
            instanceName: "RedCeilingLight",
            iD: 85,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// KitchenStuff
        /// </summary>
        public static readonly Actor KitchenStuff = new Actor(
            instanceName: "KitchenStuff",
            iD: 48,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// SuitOfArmor
        /// </summary>
        public static readonly Actor SuitOfArmor = new Actor(
            instanceName: "SuitOfArmor",
            iD: 49,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// SuitOfArmor2
        /// </summary>
        public static readonly Actor SuitOfArmor2 = new Actor(
            instanceName: "SuitOfArmor2",
            iD: 120,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// HangingCage
        /// </summary>
        public static readonly Actor HangingCage = new Actor(
            instanceName: "HangingCage",
            iD: 50,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// HangingCage2
        /// </summary>
        public static readonly Actor HangingCage2 = new Actor(
            instanceName: "HangingCage2",
            iD: 121,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// SkeletonCage
        /// </summary>
        public static readonly Actor SkeletonCage = new Actor(
            instanceName: "SkeletonCage",
            iD: 51,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// BrokenCage
        /// </summary>
        public static readonly Actor BrokenCage = new Actor(
            instanceName: "BrokenCage",
            iD: 122,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Bones1
        /// </summary>
        public static readonly Actor Bones1 = new Actor(
            instanceName: "Bones1",
            iD: 52,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Bones5
        /// </summary>
        public static readonly Actor Bones5 = new Actor(
            instanceName: "Bones5",
            iD: 123,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// BunkBed
        /// </summary>
        public static readonly Actor BunkBed = new Actor(
            instanceName: "BunkBed",
            iD: 55,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Basket
        /// </summary>
        public static readonly Actor Basket = new Actor(
            instanceName: "Basket",
            iD: 56,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// DeadRat
        /// </summary>
        public static readonly Actor DeadRat = new Actor(
            instanceName: "DeadRat",
            iD: 125,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Barrel
        /// </summary>
        public static readonly Actor Barrel = new Actor(
            instanceName: "Barrel",
            iD: 68,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// HorizontalBarrel
        /// </summary>
        public static readonly Actor HorizontalBarrel = new Actor(
            instanceName: "HorizontalBarrel",
            iD: 151,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Well
        /// </summary>
        public static readonly Actor Well = new Actor(
            instanceName: "Well",
            iD: 69,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Well2
        /// </summary>
        public static readonly Actor Well2 = new Actor(
            instanceName: "Well2",
            iD: 152,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// EmptyWell
        /// </summary>
        public static readonly Actor EmptyWell = new Actor(
            instanceName: "EmptyWell",
            iD: 70,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// EmptyWell2
        /// </summary>
        public static readonly Actor EmptyWell2 = new Actor(
            instanceName: "EmptyWell2",
            iD: 153,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Flag
        /// </summary>
        public static readonly Actor Flag = new Actor(
            instanceName: "Flag",
            iD: 72,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// TeslaCoil
        /// </summary>
        public static readonly Actor TeslaCoil = new Actor(
            instanceName: "TeslaCoil",
            iD: 127,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// CallApogee
        /// </summary>
        public static readonly Actor CallApogee = new Actor(
            instanceName: "CallApogee",
            iD: 73,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Bones2
        /// </summary>
        public static readonly Actor Bones2 = new Actor(
            instanceName: "Bones2",
            iD: 74,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Bones6
        /// </summary>
        public static readonly Actor Bones6 = new Actor(
            instanceName: "Bones6",
            iD: 129,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Bones3
        /// </summary>
        public static readonly Actor Bones3 = new Actor(
            instanceName: "Bones3",
            iD: 75,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// BareLightBulb
        /// </summary>
        public static readonly Actor BareLightBulb = new Actor(
            instanceName: "BareLightBulb",
            iD: 130,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Bones4
        /// </summary>
        public static readonly Actor Bones4 = new Actor(
            instanceName: "Bones4",
            iD: 76,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// GreenSlime
        /// </summary>
        public static readonly Actor GreenSlime = new Actor(
            instanceName: "GreenSlime",
            iD: 131,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Pots
        /// </summary>
        public static readonly Actor Pots = new Actor(
            instanceName: "Pots",
            iD: 77,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Stove
        /// </summary>
        public static readonly Actor Stove = new Actor(
            instanceName: "Stove",
            iD: 78,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Spears
        /// </summary>
        public static readonly Actor Spears = new Actor(
            instanceName: "Spears",
            iD: 79,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Vines
        /// </summary>
        public static readonly Actor Vines = new Actor(
            instanceName: "Vines",
            iD: 80,   
            category: "Decorations",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Bubbles
        /// </summary>
        public static readonly Actor Bubbles = new Actor(
            instanceName: "Bubbles",
            iD: 135,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// TruckRear
        /// </summary>
        public static readonly Actor TruckRear = new Actor(
            instanceName: "TruckRear",
            iD: 91,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// BJWasHere
        /// </summary>
        public static readonly Actor BJWasHere = new Actor(
            instanceName: "BJWasHere",
            iD: 137,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// CageWithSkulls
        /// </summary>
        public static readonly Actor CageWithSkulls = new Actor(
            instanceName: "CageWithSkulls",
            iD: 84,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// CageWithRat
        /// </summary>
        public static readonly Actor CageWithRat = new Actor(
            instanceName: "CageWithRat",
            iD: 124,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// CageWithGore
        /// </summary>
        public static readonly Actor CageWithGore = new Actor(
            instanceName: "CageWithGore",
            iD: 83,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// CageWithGore2
        /// </summary>
        public static readonly Actor CageWithGore2 = new Actor(
            instanceName: "CageWithGore2",
            iD: 119,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Skewer
        /// </summary>
        public static readonly Actor Skewer = new Actor(
            instanceName: "Skewer",
            iD: 82,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// SkullPile
        /// </summary>
        public static readonly Actor SkullPile = new Actor(
            instanceName: "SkullPile",
            iD: 150,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// CowCarcass
        /// </summary>
        public static readonly Actor CowCarcass = new Actor(
            instanceName: "CowCarcass",
            iD: 86,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// ChemicalTable
        /// </summary>
        public static readonly Actor ChemicalTable = new Actor(
            instanceName: "ChemicalTable",
            iD: 132,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// WellWithBlood
        /// </summary>
        public static readonly Actor WellWithBlood = new Actor(
            instanceName: "WellWithBlood",
            iD: 87,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// NuclearBarrel
        /// </summary>
        public static readonly Actor NuclearBarrel = new Actor(
            instanceName: "NuclearBarrel",
            iD: 133,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// SatanStatue
        /// </summary>
        public static readonly Actor SatanStatue = new Actor(
            instanceName: "SatanStatue",
            iD: 88,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// BlueColumn
        /// </summary>
        public static readonly Actor BlueColumn = new Actor(
            instanceName: "BlueColumn",
            iD: 134,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// BrownColumn
        /// </summary>
        public static readonly Actor BrownColumn = new Actor(
            instanceName: "BrownColumn",
            iD: 89,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// DevilStatue
        /// </summary>
        public static readonly Actor DevilStatue = new Actor(
            instanceName: "DevilStatue",
            iD: 136,   
            category: "Decorations",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// FakeHitler
        /// </summary>
        public static readonly Actor FakeHitler = new Actor(
            instanceName: "FakeHitler",
            iD: 18,   
            category: "Bosses",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// MechaHitler
        /// </summary>
        public static readonly Actor MechaHitler = new Actor(
            instanceName: "MechaHitler",
            iD: 19,   
            category: "Bosses",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Trans
        /// </summary>
        public static readonly Actor Trans = new Actor(
            instanceName: "Trans",
            iD: 23,   
            category: "Bosses",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// SubmarineWilly
        /// </summary>
        public static readonly Actor SubmarineWilly = new Actor(
            instanceName: "SubmarineWilly",
            iD: 99,   
            category: "Bosses",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// UberMutant
        /// </summary>
        public static readonly Actor UberMutant = new Actor(
            instanceName: "UberMutant",
            iD: 24,   
            category: "Bosses",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// TheAxe
        /// </summary>
        public static readonly Actor TheAxe = new Actor(
            instanceName: "TheAxe",
            iD: 101,   
            category: "Bosses",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Wilhelm
        /// </summary>
        public static readonly Actor Wilhelm = new Actor(
            instanceName: "Wilhelm",
            iD: 25,   
            category: "Bosses",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// ProfessorQuarkblitz
        /// </summary>
        public static readonly Actor ProfessorQuarkblitz = new Actor(
            instanceName: "ProfessorQuarkblitz",
            iD: 100,   
            category: "Bosses",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// DeathKnight
        /// </summary>
        public static readonly Actor DeathKnight = new Actor(
            instanceName: "DeathKnight",
            iD: 24,   
            category: "Bosses",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Robot
        /// </summary>
        public static readonly Actor Robot = new Actor(
            instanceName: "Robot",
            iD: 102,   
            category: "Bosses",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// SpearOfDestiny
        /// </summary>
        public static readonly Actor SpearOfDestiny = new Actor(
            instanceName: "SpearOfDestiny",
            iD: 92,   
            category: "SpearOfDestiny",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// SpearOfDestiny2
        /// </summary>
        public static readonly Actor SpearOfDestiny2 = new Actor(
            instanceName: "SpearOfDestiny2",
            iD: 138,   
            category: "SpearOfDestiny",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Clip
        /// </summary>
        public static readonly Actor Clip = new Actor(
            instanceName: "Clip",
            iD: 59,   
            category: "Ammo",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// ClipBox
        /// </summary>
        public static readonly Actor ClipBox = new Actor(
            instanceName: "ClipBox",
            iD: 90,   
            category: "Ammo",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// BlueClip
        /// </summary>
        public static readonly Actor BlueClip = new Actor(
            instanceName: "BlueClip",
            iD: 139,   
            category: "Ammo",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// ClipBox2
        /// </summary>
        public static readonly Actor ClipBox2 = new Actor(
            instanceName: "ClipBox2",
            iD: 140,   
            category: "Ammo",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Cross
        /// </summary>
        public static readonly Actor Cross = new Actor(
            instanceName: "Cross",
            iD: 62,   
            category: "Treasure",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Radio
        /// </summary>
        public static readonly Actor Radio = new Actor(
            instanceName: "Radio",
            iD: 146,   
            category: "Treasure",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Chalice
        /// </summary>
        public static readonly Actor Chalice = new Actor(
            instanceName: "Chalice",
            iD: 63,   
            category: "Treasure",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Plutonium
        /// </summary>
        public static readonly Actor Plutonium = new Actor(
            instanceName: "Plutonium",
            iD: 147,   
            category: "Treasure",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// ChestofJewels
        /// </summary>
        public static readonly Actor ChestofJewels = new Actor(
            instanceName: "ChestofJewels",
            iD: 64,   
            category: "Treasure",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// ControlPanel
        /// </summary>
        public static readonly Actor ControlPanel = new Actor(
            instanceName: "ControlPanel",
            iD: 148,   
            category: "Treasure",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Crown
        /// </summary>
        public static readonly Actor Crown = new Actor(
            instanceName: "Crown",
            iD: 65,   
            category: "Treasure",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Bomb
        /// </summary>
        public static readonly Actor Bomb = new Actor(
            instanceName: "Bomb",
            iD: 149,   
            category: "Treasure",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Hans
        /// </summary>
        public static readonly Actor Hans = new Actor(
            instanceName: "Hans",
            iD: 16,   
            category: "Bosses",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Gretel
        /// </summary>
        public static readonly Actor Gretel = new Actor(
            instanceName: "Gretel",
            iD: 20,   
            category: "Bosses",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Schabbs
        /// </summary>
        public static readonly Actor Schabbs = new Actor(
            instanceName: "Schabbs",
            iD: 17,   
            category: "Bosses",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Gift
        /// </summary>
        public static readonly Actor Gift = new Actor(
            instanceName: "Gift",
            iD: 21,   
            category: "Bosses",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// FatFace
        /// </summary>
        public static readonly Actor FatFace = new Actor(
            instanceName: "FatFace",
            iD: 22,   
            category: "Bosses",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Blinky
        /// </summary>
        public static readonly Actor Blinky = new Actor(
            instanceName: "Blinky",
            iD: 29,   
            category: "Ghosts",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Inky
        /// </summary>
        public static readonly Actor Inky = new Actor(
            instanceName: "Inky",
            iD: 32,   
            category: "Ghosts",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Pinky
        /// </summary>
        public static readonly Actor Pinky = new Actor(
            instanceName: "Pinky",
            iD: 31,   
            category: "Ghosts",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Clyde
        /// </summary>
        public static readonly Actor Clyde = new Actor(
            instanceName: "Clyde",
            iD: 30,   
            category: "Ghosts",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Spectre
        /// </summary>
        public static readonly Actor Spectre = new Actor(
            instanceName: "Spectre",
            iD: 28,   
            category: "Ghosts",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// GhoulishGhost
        /// </summary>
        public static readonly Actor GhoulishGhost = new Actor(
            instanceName: "GhoulishGhost",
            iD: 104,   
            category: "Ghosts",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// RadioactiveMist
        /// </summary>
        public static readonly Actor RadioactiveMist = new Actor(
            instanceName: "RadioactiveMist",
            iD: 157,   
            category: "Ghosts",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Guard
        /// </summary>
        public static readonly Actor Guard = new Actor(
            instanceName: "Guard",
            iD: 11,   
            category: "Guards",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// GreenGuard
        /// </summary>
        public static readonly Actor GreenGuard = new Actor(
            instanceName: "GreenGuard",
            iD: 93,   
            category: "Guards",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// DeadGuard
        /// </summary>
        public static readonly Actor DeadGuard = new Actor(
            instanceName: "DeadGuard",
            iD: 81,   
            category: "Guards",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// DeadGreenGuard
        /// </summary>
        public static readonly Actor DeadGreenGuard = new Actor(
            instanceName: "DeadGreenGuard",
            iD: 98,   
            category: "Guards",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Dog
        /// </summary>
        public static readonly Actor Dog = new Actor(
            instanceName: "Dog",
            iD: 14,   
            category: "Guards",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Doberman
        /// </summary>
        public static readonly Actor Doberman = new Actor(
            instanceName: "Doberman",
            iD: 95,   
            category: "Guards",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Officer
        /// </summary>
        public static readonly Actor Officer = new Actor(
            instanceName: "Officer",
            iD: 12,   
            category: "Guards",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// LostOfficer
        /// </summary>
        public static readonly Actor LostOfficer = new Actor(
            instanceName: "LostOfficer",
            iD: 97,   
            category: "Guards",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Mutant
        /// </summary>
        public static readonly Actor Mutant = new Actor(
            instanceName: "Mutant",
            iD: 15,   
            category: "Guards",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// GunBat
        /// </summary>
        public static readonly Actor GunBat = new Actor(
            instanceName: "GunBat",
            iD: 96,   
            category: "Guards",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// WolfensteinSS
        /// </summary>
        public static readonly Actor WolfensteinSS = new Actor(
            instanceName: "WolfensteinSS",
            iD: 13,   
            category: "Guards",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Schutzstafell
        /// </summary>
        public static readonly Actor Schutzstafell = new Actor(
            instanceName: "Schutzstafell",
            iD: 94,   
            category: "Guards",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// DogFood
        /// </summary>
        public static readonly Actor DogFood = new Actor(
            instanceName: "DogFood",
            iD: 39,   
            category: "Health",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// DogFood2
        /// </summary>
        public static readonly Actor DogFood2 = new Actor(
            instanceName: "DogFood2",
            iD: 111,   
            category: "Health",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Food
        /// </summary>
        public static readonly Actor Food = new Actor(
            instanceName: "Food",
            iD: 57,   
            category: "Health",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Food2
        /// </summary>
        public static readonly Actor Food2 = new Actor(
            instanceName: "Food2",
            iD: 142,   
            category: "Health",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Medikit
        /// </summary>
        public static readonly Actor Medikit = new Actor(
            instanceName: "Medikit",
            iD: 58,   
            category: "Health",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Medikit2
        /// </summary>
        public static readonly Actor Medikit2 = new Actor(
            instanceName: "Medikit2",
            iD: 143,   
            category: "Health",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// OneUp
        /// </summary>
        public static readonly Actor OneUp = new Actor(
            instanceName: "OneUp",
            iD: 66,   
            category: "Health",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// OneUpPill
        /// </summary>
        public static readonly Actor OneUpPill = new Actor(
            instanceName: "OneUpPill",
            iD: 144,   
            category: "Health",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Blood
        /// </summary>
        public static readonly Actor Blood = new Actor(
            instanceName: "Blood",
            iD: 67,   
            category: "Health",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Blood2
        /// </summary>
        public static readonly Actor Blood2 = new Actor(
            instanceName: "Blood2",
            iD: 145,   
            category: "Health",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// Gibs
        /// </summary>
        public static readonly Actor Gibs = new Actor(
            instanceName: "Gibs",
            iD: 71,   
            category: "Health",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// Gibs2
        /// </summary>
        public static readonly Actor Gibs2 = new Actor(
            instanceName: "Gibs2",
            iD: 126,   
            category: "Health",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// GoldKey
        /// </summary>
        public static readonly Actor GoldKey = new Actor(
            instanceName: "GoldKey",
            iD: 53,   
            category: "Keys",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// YellowKey
        /// </summary>
        public static readonly Actor YellowKey = new Actor(
            instanceName: "YellowKey",
            iD: 154,   
            category: "Keys",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// SilverKey
        /// </summary>
        public static readonly Actor SilverKey = new Actor(
            instanceName: "SilverKey",
            iD: 54,   
            category: "Keys",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// CyanKey
        /// </summary>
        public static readonly Actor CyanKey = new Actor(
            instanceName: "CyanKey",
            iD: 155,   
            category: "Keys",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// MachineGun
        /// </summary>
        public static readonly Actor MachineGun = new Actor(
            instanceName: "MachineGun",
            iD: 60,   
            category: "Weapons",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// BlueAK47
        /// </summary>
        public static readonly Actor BlueAK47 = new Actor(
            instanceName: "BlueAK47",
            iD: 141,   
            category: "Weapons",   
            wolf3D: false,   
            prefix: ""  
        );
        /// <summary>
        /// GatlingGunUpgrade
        /// </summary>
        public static readonly Actor GatlingGunUpgrade = new Actor(
            instanceName: "GatlingGunUpgrade",
            iD: 61,   
            category: "Weapons",   
            wolf3D: true,   
            prefix: ""  
        );
        /// <summary>
        /// BlueGatlingGunUpgrade
        /// </summary>
        public static readonly Actor BlueGatlingGunUpgrade = new Actor(
            instanceName: "BlueGatlingGunUpgrade",
            iD: 156,   
            category: "Weapons",   
            wolf3D: false,   
            prefix: ""  
        );

        private Actor(
            string instanceName,
            System.Int32 iD,   
            System.String category,   
            System.Boolean wolf3D,   
            System.String prefix  
        )
        {
            _instanceName = instanceName;
            ID = iD; 
            Category = category; 
            Wolf3D = wolf3D; 
            Prefix = prefix; 
        }

        /// <summary>
        /// Returns the name of this instance.
        /// </summary>
        /// <returns>
        /// A <see cref="System.String" /> that represents this instance.
        /// </returns>
        public override string ToString()
        {
            return _instanceName;
        }

        /// <summary>
        /// Returns all the enumeration values.
        /// </summary>
        public static System.Collections.Generic.IEnumerable<Actor> GetAll()
        {
            yield return Player1Start;
            yield return PatrolPoint;
            yield return AngelOfDeath;
            yield return DevilIncarnate;
            yield return Puddle;
            yield return Puddle2;
            yield return GreenBarrel;
            yield return HorizontalGreenBarrel;
            yield return TableWithChairs;
            yield return TableWithChairs2;
            yield return FloorLamp;
            yield return TallFloorLamp;
            yield return Chandelier;
            yield return Chandelier2;
            yield return HangedMan;
            yield return HangedMan2;
            yield return WhitePillar;
            yield return CrackedPillar;
            yield return GreenPlant;
            yield return GreenPlant2;
            yield return SkeletonFlat;
            yield return SkeletonFlat2;
            yield return Sink;
            yield return BrownPlant;
            yield return BrownPlant2;
            yield return Vase;
            yield return Vase2;
            yield return BareTable;
            yield return MetalTable;
            yield return CeilingLight;
            yield return CeilingLight2;
            yield return RedCeilingLight;
            yield return KitchenStuff;
            yield return SuitOfArmor;
            yield return SuitOfArmor2;
            yield return HangingCage;
            yield return HangingCage2;
            yield return SkeletonCage;
            yield return BrokenCage;
            yield return Bones1;
            yield return Bones5;
            yield return BunkBed;
            yield return Basket;
            yield return DeadRat;
            yield return Barrel;
            yield return HorizontalBarrel;
            yield return Well;
            yield return Well2;
            yield return EmptyWell;
            yield return EmptyWell2;
            yield return Flag;
            yield return TeslaCoil;
            yield return CallApogee;
            yield return Bones2;
            yield return Bones6;
            yield return Bones3;
            yield return BareLightBulb;
            yield return Bones4;
            yield return GreenSlime;
            yield return Pots;
            yield return Stove;
            yield return Spears;
            yield return Vines;
            yield return Bubbles;
            yield return TruckRear;
            yield return BJWasHere;
            yield return CageWithSkulls;
            yield return CageWithRat;
            yield return CageWithGore;
            yield return CageWithGore2;
            yield return Skewer;
            yield return SkullPile;
            yield return CowCarcass;
            yield return ChemicalTable;
            yield return WellWithBlood;
            yield return NuclearBarrel;
            yield return SatanStatue;
            yield return BlueColumn;
            yield return BrownColumn;
            yield return DevilStatue;
            yield return FakeHitler;
            yield return MechaHitler;
            yield return Trans;
            yield return SubmarineWilly;
            yield return UberMutant;
            yield return TheAxe;
            yield return Wilhelm;
            yield return ProfessorQuarkblitz;
            yield return DeathKnight;
            yield return Robot;
            yield return SpearOfDestiny;
            yield return SpearOfDestiny2;
            yield return Clip;
            yield return ClipBox;
            yield return BlueClip;
            yield return ClipBox2;
            yield return Cross;
            yield return Radio;
            yield return Chalice;
            yield return Plutonium;
            yield return ChestofJewels;
            yield return ControlPanel;
            yield return Crown;
            yield return Bomb;
            yield return Hans;
            yield return Gretel;
            yield return Schabbs;
            yield return Gift;
            yield return FatFace;
            yield return Blinky;
            yield return Inky;
            yield return Pinky;
            yield return Clyde;
            yield return Spectre;
            yield return GhoulishGhost;
            yield return RadioactiveMist;
            yield return Guard;
            yield return GreenGuard;
            yield return DeadGuard;
            yield return DeadGreenGuard;
            yield return Dog;
            yield return Doberman;
            yield return Officer;
            yield return LostOfficer;
            yield return Mutant;
            yield return GunBat;
            yield return WolfensteinSS;
            yield return Schutzstafell;
            yield return DogFood;
            yield return DogFood2;
            yield return Food;
            yield return Food2;
            yield return Medikit;
            yield return Medikit2;
            yield return OneUp;
            yield return OneUpPill;
            yield return Blood;
            yield return Blood2;
            yield return Gibs;
            yield return Gibs2;
            yield return GoldKey;
            yield return YellowKey;
            yield return SilverKey;
            yield return CyanKey;
            yield return MachineGun;
            yield return BlueAK47;
            yield return GatlingGunUpgrade;
            yield return BlueGatlingGunUpgrade;
        }
    }
}

