// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>

namespace Tiledriver.Wolf3D
{
    /// <summary>
    /// WolfThing
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "RichEnumGenerator", "1.0.0.0" )]
    public sealed partial class WolfThing
    {
        private readonly string _instanceName;
        private readonly System.Int32 _id;

        /// <summary>
        /// Player1Start
        /// </summary>
        public static readonly WolfThing Player1Start = new WolfThing(
            instanceName: "Player1Start",
            id: 1  
        );
        /// <summary>
        /// PatrolPoint
        /// </summary>
        public static readonly WolfThing PatrolPoint = new WolfThing(
            instanceName: "PatrolPoint",
            id: 10  
        );
        /// <summary>
        /// Guard
        /// </summary>
        public static readonly WolfThing Guard = new WolfThing(
            instanceName: "Guard",
            id: 11  
        );
        /// <summary>
        /// Officer
        /// </summary>
        public static readonly WolfThing Officer = new WolfThing(
            instanceName: "Officer",
            id: 12  
        );
        /// <summary>
        /// SSGuard
        /// </summary>
        public static readonly WolfThing SSGuard = new WolfThing(
            instanceName: "SSGuard",
            id: 13  
        );
        /// <summary>
        /// Dog
        /// </summary>
        public static readonly WolfThing Dog = new WolfThing(
            instanceName: "Dog",
            id: 14  
        );
        /// <summary>
        /// Mutant
        /// </summary>
        public static readonly WolfThing Mutant = new WolfThing(
            instanceName: "Mutant",
            id: 15  
        );
        /// <summary>
        /// Hans
        /// </summary>
        public static readonly WolfThing Hans = new WolfThing(
            instanceName: "Hans",
            id: 16  
        );
        /// <summary>
        /// Schabbs
        /// </summary>
        public static readonly WolfThing Schabbs = new WolfThing(
            instanceName: "Schabbs",
            id: 17  
        );
        /// <summary>
        /// FakeHitler
        /// </summary>
        public static readonly WolfThing FakeHitler = new WolfThing(
            instanceName: "FakeHitler",
            id: 18  
        );
        /// <summary>
        /// Hitler
        /// </summary>
        public static readonly WolfThing Hitler = new WolfThing(
            instanceName: "Hitler",
            id: 19  
        );
        /// <summary>
        /// Gretel
        /// </summary>
        public static readonly WolfThing Gretel = new WolfThing(
            instanceName: "Gretel",
            id: 20  
        );
        /// <summary>
        /// Gift
        /// </summary>
        public static readonly WolfThing Gift = new WolfThing(
            instanceName: "Gift",
            id: 21  
        );
        /// <summary>
        /// Fatface
        /// </summary>
        public static readonly WolfThing Fatface = new WolfThing(
            instanceName: "Fatface",
            id: 22  
        );
        /// <summary>
        /// PacmanGhostBlinky
        /// </summary>
        public static readonly WolfThing PacmanGhostBlinky = new WolfThing(
            instanceName: "PacmanGhostBlinky",
            id: 29  
        );
        /// <summary>
        /// PacmanGhostClyde
        /// </summary>
        public static readonly WolfThing PacmanGhostClyde = new WolfThing(
            instanceName: "PacmanGhostClyde",
            id: 30  
        );
        /// <summary>
        /// PacmanGhostPinky
        /// </summary>
        public static readonly WolfThing PacmanGhostPinky = new WolfThing(
            instanceName: "PacmanGhostPinky",
            id: 31  
        );
        /// <summary>
        /// PacmanGhostInky
        /// </summary>
        public static readonly WolfThing PacmanGhostInky = new WolfThing(
            instanceName: "PacmanGhostInky",
            id: 32  
        );
        /// <summary>
        /// Puddle
        /// </summary>
        public static readonly WolfThing Puddle = new WolfThing(
            instanceName: "Puddle",
            id: 33  
        );
        /// <summary>
        /// GreenBarrel
        /// </summary>
        public static readonly WolfThing GreenBarrel = new WolfThing(
            instanceName: "GreenBarrel",
            id: 34  
        );
        /// <summary>
        /// TableWithChairs
        /// </summary>
        public static readonly WolfThing TableWithChairs = new WolfThing(
            instanceName: "TableWithChairs",
            id: 35  
        );
        /// <summary>
        /// FloorLamp
        /// </summary>
        public static readonly WolfThing FloorLamp = new WolfThing(
            instanceName: "FloorLamp",
            id: 36  
        );
        /// <summary>
        /// Chandelier
        /// </summary>
        public static readonly WolfThing Chandelier = new WolfThing(
            instanceName: "Chandelier",
            id: 37  
        );
        /// <summary>
        /// HangedMan
        /// </summary>
        public static readonly WolfThing HangedMan = new WolfThing(
            instanceName: "HangedMan",
            id: 38  
        );
        /// <summary>
        /// DogFood
        /// </summary>
        public static readonly WolfThing DogFood = new WolfThing(
            instanceName: "DogFood",
            id: 39  
        );
        /// <summary>
        /// WhitePillar
        /// </summary>
        public static readonly WolfThing WhitePillar = new WolfThing(
            instanceName: "WhitePillar",
            id: 40  
        );
        /// <summary>
        /// GreenPlant
        /// </summary>
        public static readonly WolfThing GreenPlant = new WolfThing(
            instanceName: "GreenPlant",
            id: 41  
        );
        /// <summary>
        /// SkeletonFlat
        /// </summary>
        public static readonly WolfThing SkeletonFlat = new WolfThing(
            instanceName: "SkeletonFlat",
            id: 42  
        );
        /// <summary>
        /// Sink
        /// </summary>
        public static readonly WolfThing Sink = new WolfThing(
            instanceName: "Sink",
            id: 43  
        );
        /// <summary>
        /// BrownPlant
        /// </summary>
        public static readonly WolfThing BrownPlant = new WolfThing(
            instanceName: "BrownPlant",
            id: 44  
        );
        /// <summary>
        /// Vase
        /// </summary>
        public static readonly WolfThing Vase = new WolfThing(
            instanceName: "Vase",
            id: 45  
        );
        /// <summary>
        /// Table
        /// </summary>
        public static readonly WolfThing Table = new WolfThing(
            instanceName: "Table",
            id: 46  
        );
        /// <summary>
        /// CeilingLight
        /// </summary>
        public static readonly WolfThing CeilingLight = new WolfThing(
            instanceName: "CeilingLight",
            id: 47  
        );
        /// <summary>
        /// KitchenStuff
        /// </summary>
        public static readonly WolfThing KitchenStuff = new WolfThing(
            instanceName: "KitchenStuff",
            id: 48  
        );
        /// <summary>
        /// SuitOfArmor
        /// </summary>
        public static readonly WolfThing SuitOfArmor = new WolfThing(
            instanceName: "SuitOfArmor",
            id: 49  
        );
        /// <summary>
        /// EmptyCage
        /// </summary>
        public static readonly WolfThing EmptyCage = new WolfThing(
            instanceName: "EmptyCage",
            id: 50  
        );
        /// <summary>
        /// CageWithSkeleton
        /// </summary>
        public static readonly WolfThing CageWithSkeleton = new WolfThing(
            instanceName: "CageWithSkeleton",
            id: 51  
        );
        /// <summary>
        /// Bones1
        /// </summary>
        public static readonly WolfThing Bones1 = new WolfThing(
            instanceName: "Bones1",
            id: 52  
        );
        /// <summary>
        /// GoldKey
        /// </summary>
        public static readonly WolfThing GoldKey = new WolfThing(
            instanceName: "GoldKey",
            id: 53  
        );
        /// <summary>
        /// SilverKey
        /// </summary>
        public static readonly WolfThing SilverKey = new WolfThing(
            instanceName: "SilverKey",
            id: 54  
        );
        /// <summary>
        /// Bed
        /// </summary>
        public static readonly WolfThing Bed = new WolfThing(
            instanceName: "Bed",
            id: 55  
        );
        /// <summary>
        /// Basket
        /// </summary>
        public static readonly WolfThing Basket = new WolfThing(
            instanceName: "Basket",
            id: 56  
        );
        /// <summary>
        /// Food
        /// </summary>
        public static readonly WolfThing Food = new WolfThing(
            instanceName: "Food",
            id: 57  
        );
        /// <summary>
        /// FirstAidKit
        /// </summary>
        public static readonly WolfThing FirstAidKit = new WolfThing(
            instanceName: "FirstAidKit",
            id: 58  
        );
        /// <summary>
        /// Clip
        /// </summary>
        public static readonly WolfThing Clip = new WolfThing(
            instanceName: "Clip",
            id: 59  
        );
        /// <summary>
        /// MachineGun
        /// </summary>
        public static readonly WolfThing MachineGun = new WolfThing(
            instanceName: "MachineGun",
            id: 60  
        );
        /// <summary>
        /// GatlingGun
        /// </summary>
        public static readonly WolfThing GatlingGun = new WolfThing(
            instanceName: "GatlingGun",
            id: 61  
        );
        /// <summary>
        /// Cross
        /// </summary>
        public static readonly WolfThing Cross = new WolfThing(
            instanceName: "Cross",
            id: 62  
        );
        /// <summary>
        /// Chalice
        /// </summary>
        public static readonly WolfThing Chalice = new WolfThing(
            instanceName: "Chalice",
            id: 63  
        );
        /// <summary>
        /// ChestOfJewels
        /// </summary>
        public static readonly WolfThing ChestOfJewels = new WolfThing(
            instanceName: "ChestOfJewels",
            id: 64  
        );
        /// <summary>
        /// Crown
        /// </summary>
        public static readonly WolfThing Crown = new WolfThing(
            instanceName: "Crown",
            id: 65  
        );
        /// <summary>
        /// ExtraLife
        /// </summary>
        public static readonly WolfThing ExtraLife = new WolfThing(
            instanceName: "ExtraLife",
            id: 66  
        );
        /// <summary>
        /// Blood
        /// </summary>
        public static readonly WolfThing Blood = new WolfThing(
            instanceName: "Blood",
            id: 67  
        );
        /// <summary>
        /// Barrel
        /// </summary>
        public static readonly WolfThing Barrel = new WolfThing(
            instanceName: "Barrel",
            id: 68  
        );
        /// <summary>
        /// Well
        /// </summary>
        public static readonly WolfThing Well = new WolfThing(
            instanceName: "Well",
            id: 69  
        );
        /// <summary>
        /// EmptyWell
        /// </summary>
        public static readonly WolfThing EmptyWell = new WolfThing(
            instanceName: "EmptyWell",
            id: 70  
        );
        /// <summary>
        /// Gibs
        /// </summary>
        public static readonly WolfThing Gibs = new WolfThing(
            instanceName: "Gibs",
            id: 71  
        );
        /// <summary>
        /// Flag
        /// </summary>
        public static readonly WolfThing Flag = new WolfThing(
            instanceName: "Flag",
            id: 72  
        );
        /// <summary>
        /// CallApogee
        /// </summary>
        public static readonly WolfThing CallApogee = new WolfThing(
            instanceName: "CallApogee",
            id: 73  
        );
        /// <summary>
        /// Bones2
        /// </summary>
        public static readonly WolfThing Bones2 = new WolfThing(
            instanceName: "Bones2",
            id: 74  
        );
        /// <summary>
        /// Bones3
        /// </summary>
        public static readonly WolfThing Bones3 = new WolfThing(
            instanceName: "Bones3",
            id: 75  
        );
        /// <summary>
        /// Bones4
        /// </summary>
        public static readonly WolfThing Bones4 = new WolfThing(
            instanceName: "Bones4",
            id: 76  
        );
        /// <summary>
        /// Pots
        /// </summary>
        public static readonly WolfThing Pots = new WolfThing(
            instanceName: "Pots",
            id: 77  
        );
        /// <summary>
        /// Stove
        /// </summary>
        public static readonly WolfThing Stove = new WolfThing(
            instanceName: "Stove",
            id: 78  
        );
        /// <summary>
        /// Spears
        /// </summary>
        public static readonly WolfThing Spears = new WolfThing(
            instanceName: "Spears",
            id: 79  
        );
        /// <summary>
        /// Vines
        /// </summary>
        public static readonly WolfThing Vines = new WolfThing(
            instanceName: "Vines",
            id: 80  
        );
        /// <summary>
        /// DeadGuard
        /// </summary>
        public static readonly WolfThing DeadGuard = new WolfThing(
            instanceName: "DeadGuard",
            id: 81  
        );

        private WolfThing(
            string instanceName,
            System.Int32 id  
        )
        {
            _instanceName = instanceName;
            _id = id; 
        }

        /// <summary>
        /// Returns the name of this instance.
        /// </summary>
        /// <returns>
        /// A <see cref="System.String" /> that represents this instance.
        /// </returns>
        public override string ToString()
        {
            return _instanceName;
        }

        /// <summary>
        /// Returns all the enumeration values.
        /// </summary>
        public static System.Collections.Generic.IEnumerable<WolfThing> GetAll()
        {
            yield return Player1Start;
            yield return PatrolPoint;
            yield return Guard;
            yield return Officer;
            yield return SSGuard;
            yield return Dog;
            yield return Mutant;
            yield return Hans;
            yield return Schabbs;
            yield return FakeHitler;
            yield return Hitler;
            yield return Gretel;
            yield return Gift;
            yield return Fatface;
            yield return PacmanGhostBlinky;
            yield return PacmanGhostClyde;
            yield return PacmanGhostPinky;
            yield return PacmanGhostInky;
            yield return Puddle;
            yield return GreenBarrel;
            yield return TableWithChairs;
            yield return FloorLamp;
            yield return Chandelier;
            yield return HangedMan;
            yield return DogFood;
            yield return WhitePillar;
            yield return GreenPlant;
            yield return SkeletonFlat;
            yield return Sink;
            yield return BrownPlant;
            yield return Vase;
            yield return Table;
            yield return CeilingLight;
            yield return KitchenStuff;
            yield return SuitOfArmor;
            yield return EmptyCage;
            yield return CageWithSkeleton;
            yield return Bones1;
            yield return GoldKey;
            yield return SilverKey;
            yield return Bed;
            yield return Basket;
            yield return Food;
            yield return FirstAidKit;
            yield return Clip;
            yield return MachineGun;
            yield return GatlingGun;
            yield return Cross;
            yield return Chalice;
            yield return ChestOfJewels;
            yield return Crown;
            yield return ExtraLife;
            yield return Blood;
            yield return Barrel;
            yield return Well;
            yield return EmptyWell;
            yield return Gibs;
            yield return Flag;
            yield return CallApogee;
            yield return Bones2;
            yield return Bones3;
            yield return Bones4;
            yield return Pots;
            yield return Stove;
            yield return Spears;
            yield return Vines;
            yield return DeadGuard;
        }
    }
}

